version: 2
jobs:
    build:
        environment:
            NODE_ENV: development
        docker:
            - image: circleci/node:14.15
        steps:
            - checkout

            - restore_cache:
                  keys:
                      - yarn-packages-v1-{{ checksum "yarn.lock" }}
                      - yarn-packages-v1-

            - run:
                  name: Install dependencies
                  command: yarn install --network-concurrency 1
                  when: always

            - save_cache:
                  paths:
                      - ~/.cache/yarn
                  key: yarn-packages-v1-{{ checksum "yarn.lock" }}

            - run:
                  name: Build
                  command: yarn build
                  when: always

            - run:
                  name: Run lint
                  command: yarn lint
                  when: always

            - run:
                  name: Run tests
                  command: NETWORK="testnet" yarn test
                  no_output_timeout: 30m
                  when: always
