name: build

on: [push]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [14.x, 16.x, 18.x]
                os: [ubuntu-latest, windows-latest]
        name: Build on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "yarn"
            - name: Install dependencies
              run: |
                  yarn install --network-concurrency 1
            - name: Lint
              run: |
                  yarn lint
            - name: Build
              run: |
                  yarn build
